### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by miraserver** [null93/chrome-milk#22]
Hello, i know someone create Milk for firefox and currently here is only old version with bugs (import cookie)...
any chance compile for Firefox ? thanx

**Comment by null93** [comment]
Hey,

The extension listed for Firefox has nothing to do with me. I wrote this extension and licensed it under the MIT license, so basically anyone can do what they want with it for free. Someone decided to port it to Firefox which is great!

I am very hesitant to port it to Firefox myself since I do not use Firefox and would not be able to maintain the same level of quality that I do with this extension. That being said, It might already be Firefox compatible sans the manifest file.

I will do a little research later on and decide if this is something that I would like to do (and reply here). Thanks for bringing it to my attention.

**Comment by miraserver** [comment]
yeap, i understand. Iv use both - chrome and firefox : that's why iv asked for.
So new v2.xx is perfect, nice and easy interface and most important for me - works with import many another json cookie. Its good because iv tested about 8 most popular cookie import/export plugins and only milk compatible with most of cookie json files generated by other.

**Comment by null93** [comment]
Firstly, thank you for using MILK for Chrome! I worked really hard making version 2.x look and function the way it does and it is nice to hear that you like it!

I looked into porting it to Firefox, and while I did get a version of this extension semi-working on Firefox, it will take a lot of work trying to port it over. It is currently unusable and really slow and laggy. Unfortunately, this is not something that I want to do right now since I do not use Firefox and it would take a lot of effort trying to make it work there. Also. I do not want to put out a product that does not function well. Hope you understand. If any plans change in the future, I will be sure to re-open this  issue and let you know.

If you do enjoy using this extension on Google Chrome, please consider leaving a review on the [Chrome WebStore](https://chrome.google.com/webstore/detail/milk-%E2%80%94-cookie-manager/haipckejfdppjfblgondaakgckohcihp). It would help me a lot. Thank you!

**Comment by null93** [comment]
I am gonna reopen this since I think I was experiencing the effects of https://github.com/null93/chrome-milk/issues/23 while trying to port it over. I'll update this ticket with some updates when I can.

**Comment by null93** [comment]
I am still trying to see if this one will work. I've done a lot to make it compatible with both chrome and Mozilla but there is still more work that needs to be done.

**Comment by null93** [comment]
Finally found the issue with the infinite loop in Firefox. Basically there is a _bug_ in Firefox that does not remove expired cookies and this extension tries to reload the cookies when it encounters an expired one (since there is no listener for regular expiration). Firefox bug can be tracked here:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1388873
- https://bugzilla.mozilla.org/show_bug.cgi?id=1669716

We can avoid this by simply filtering the cookies that `browser.cookies.getAll` returns based on the expiration date.

There is some more work to be done to make this extension compatible with Firefox. This would involve replacing the `datetime-local` component in the cookie editor panel. As mentioned in #10, I really do not want to do that since I like the UX of that component and how it is implemented in chrome. I will have to see what I can do about that one.

**Comment by null93** [comment]
@miraserver Took quite a bit of work but this extension should now be Firefox compatible. Will publish next release in Firefox Extension Store.
