### ISSUE TITLE
Add Option To Use DD/MM/YY Instead Of MM/DD/YY As A Date Dormat

### ISSUE THREAD

**Issue by cpuuntery** [null93/chrome-milk#25]

**Comment by null93** [comment]
Hey, thanks for using the extension! I am in full support of this feature. I will try to implement it in the next release!

**Comment by null93** [comment]
After looking into this request some more, here are my findings. Below are the two places where a timestamp is displayed to the user:

<img width="551" alt="Screen Shot 2020-12-21 at 11 11 29 PM" src="https://user-images.githubusercontent.com/5500199/102851748-3e30fd80-43e2-11eb-877c-97a25d1bf451.png">
<img width="550" alt="Screen Shot 2020-12-21 at 11 13 07 PM" src="https://user-images.githubusercontent.com/5500199/102851749-3ec99400-43e2-11eb-9a3f-3653a27b3531.png">

In both cases these timestamps are location specific and change to accommodate the normal format for displaying date/time for said user. In particular <span>#</span>2 is an input with type **datetime-local** which is completely managed by the browser and does not allow custom formatting. I really like the UX of the datetime-local element so I do not see myself changing it for something else. For that reason, it would really be confusing for UX if we change <span>#</span>1 but do not change <span>#</span>2. Considering that they are both are location sensitive already, I do not see any reason to change them.

Thank you for your input; it is much appreciated!

**Comment by cpuuntery** [comment]
@null93 
**I did say to add an option. And not to make it the default behaviour.** So users who are fine with the UX as it is will not be affected. And i very much sure even if the browser report MM/DD/YY you can use JavaScript to move DD and MM. before outputting them

**Comment by null93** [comment]
@cpuuntery 

> I did say to add an option. And not to make it the default behaviour. So users who are fine with the UX as it is will not be affected.

I cannot make it optional if I cannot change the format even manually. From the best of my knowledge, there is no javascript that can change the format of `<input type="datetime-local" />`. If you would like to prove me wrong, please do so and I will be happy to change it. Unfortunately, I am pretty positive that this element does not support a custom format and is fully managed by the browser.

> And i very much sure even if the browser report MM/DD/YY you can use JavaScript to move DD and MM. before outputting them

These values are not interchangeable because of their ranges (MM is 1-12 & DD is obviously more than 12).

Again, I am sorry that this is something I cannot implement. I was on board initially, but if it means changing the UX of the input element, I simply do not want to do that. Thanks for using the extension! Have a great day!
